In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../input/80-cereals/cereal.csv").copy()

In [2]:
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

In [3]:
df.name.unique()

array(['100% Bran', '100% Natural Bran', 'All-Bran',
       'All-Bran with Extra Fiber', 'Almond Delight',
       'Apple Cinnamon Cheerios', 'Apple Jacks', 'Basic 4', 'Bran Chex',
       'Bran Flakes', "Cap'n'Crunch", 'Cheerios', 'Cinnamon Toast Crunch',
       'Clusters', 'Cocoa Puffs', 'Corn Chex', 'Corn Flakes', 'Corn Pops',
       'Count Chocula', "Cracklin' Oat Bran", 'Cream of Wheat (Quick)',
       'Crispix', 'Crispy Wheat & Raisins', 'Double Chex', 'Froot Loops',
       'Frosted Flakes', 'Frosted Mini-Wheats',
       'Fruit & Fibre Dates; Walnuts; and Oats', 'Fruitful Bran',
       'Fruity Pebbles', 'Golden Crisp', 'Golden Grahams',
       'Grape Nuts Flakes', 'Grape-Nuts', 'Great Grains Pecan',
       'Honey Graham Ohs', 'Honey Nut Cheerios', 'Honey-comb',
       'Just Right Crunchy  Nuggets', 'Just Right Fruit & Nut', 'Kix',
       'Life', 'Lucky Charms', 'Maypo',
       'Muesli Raisins; Dates; & Almonds',
       'Muesli Raisins; Peaches; & Pecans', 'Mueslix Crispy Blend',
       'Multi-Grain Cheerios', 'Nut&Honey Crunch',
       'Nutri-Grain Almond-Raisin', 'Nutri-grain Wheat',
       'Oatmeal Raisin Crisp', 'Post Nat. Raisin Bran', 'Product 19',
       'Puffed Rice', 'Puffed Wheat', 'Quaker Oat Squares',
       'Quaker Oatmeal', 'Raisin Bran', 'Raisin Nut Bran',
       'Raisin Squares', 'Rice Chex', 'Rice Krispies', 'Shredded Wheat',
       "Shredded Wheat 'n'Bran", 'Shredded Wheat spoon size', 'Smacks',
       'Special K', 'Strawberry Fruit Wheats', 'Total Corn Flakes',
       'Total Raisin Bran', 'Total Whole Grain', 'Triples', 'Trix',
       'Wheat Chex', 'Wheaties', 'Wheaties Honey Gold'], dtype=object)

In [4]:
df.isnull().sum()

name        0
mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       0
sugars      0
potass      0
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
calories,77.0,106.883117,19.484119,50.000000,100.000000,110.000000,110.000000,160.000000
protein,77.0,2.545455,1.094790,1.000000,2.000000,3.000000,3.000000,6.000000
fat,77.0,1.012987,1.006473,0.000000,0.000000,1.000000,2.000000,5.000000
sodium,77.0,159.675325,83.832295,0.000000,130.000000,180.000000,210.000000,320.000000
fiber,77.0,2.151948,2.383364,0.000000,1.000000,2.000000,3.000000,14.000000
carbo,77.0,14.597403,4.278956,-1.000000,12.000000,14.000000,17.000000,23.000000
sugars,77.0,6.922078,4.444885,-1.000000,3.000000,7.000000,11.000000,15.000000
potass,77.0,96.077922,71.286813,-1.000000,40.000000,90.000000,120.000000,330.000000
vitamins,77.0,28.246753,22.342523,0.000000,25.000000,25.000000,25.000000,100.000000
shelf,77.0,2.207792,0.832524,1.000000,1.000000,2.000000,3.000000,3.000000
weight,77.0,1.029610,0.150477,0.500000,1.000000,1.000000,1.000000,1.500000
cups,77.0,0.821039,0.232716,0.250000,0.670000,0.750000,1.000000,1.500000
rating,77.0,42.665705,14.047289,18.042851,33.174094,40.400208,50.828392,93.704912

In [6]:
dummies = df['name'].str.get_dummies()

In [7]:
dummies

,100% Bran,100% Natural Bran,All-Bran,All-Bran with Extra Fiber,Almond Delight,Apple Cinnamon Cheerios,Apple Jacks,Basic 4,Bran Chex,Bran Flakes,...,Special K,Strawberry Fruit Wheats,Total Corn Flakes,Total Raisin Bran,Total Whole Grain,Triples,Trix,Wheat Chex,Wheaties,Wheaties Honey Gold
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
73,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
74,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
75,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
76,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [8]:
df = pd.concat([df,dummies],axis=1)

In [9]:
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,...,Special K,Strawberry Fruit Wheats,Total Corn Flakes,Total Raisin Bran,Total Whole Grain,Triples,Trix,Wheat Chex,Wheaties,Wheaties Honey Gold
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,...,0,0,0,0,0,0,0,0,0,0
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,...,0,0,0,0,0,0,0,0,0,0
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,...,0,0,0,0,0,0,0,0,0,0
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,...,0,0,0,0,0,0,0,0,0,0
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df=df.drop(['name'],axis=1)

In [11]:
dummies_mfr = df['mfr'].str.get_dummies()

In [12]:
df=pd.concat([df,dummies_mfr],axis=1)

In [13]:
df = df.drop(['mfr'],axis=1)

In [14]:
df.head()

,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,...,Wheat Chex,Wheaties,Wheaties Honey Gold,A,G,K,N,P,Q,R
0,C,70,4,1,130,10.0,5.0,6,280,25,...,0,0,0,0,0,0,1,0,0,0
1,C,120,3,5,15,2.0,8.0,8,135,0,...,0,0,0,0,0,0,0,0,1,0
2,C,70,4,1,260,9.0,7.0,5,320,25,...,0,0,0,0,0,1,0,0,0,0
3,C,50,4,0,140,14.0,8.0,0,330,25,...,0,0,0,0,0,1,0,0,0,0
4,C,110,2,2,200,1.0,14.0,8,-1,25,...,0,0,0,0,0,0,0,0,0,1

In [15]:
dummies_c = df['type'].str.get_dummies()

In [16]:
df = pd.concat([df,dummies_c],axis=1)

In [17]:
df = df.drop(['type'],axis=1)

In [18]:
df.head()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,...,Wheaties Honey Gold,A,G,K,N,P,Q,R,C,H
0,70,4,1,130,10.0,5.0,6,280,25,3,...,0,0,0,0,1,0,0,0,1,0
1,120,3,5,15,2.0,8.0,8,135,0,3,...,0,0,0,0,0,0,1,0,1,0
2,70,4,1,260,9.0,7.0,5,320,25,3,...,0,0,0,1,0,0,0,0,1,0
3,50,4,0,140,14.0,8.0,0,330,25,3,...,0,0,0,1,0,0,0,0,1,0
4,110,2,2,200,1.0,14.0,8,-1,25,3,...,0,0,0,0,0,0,0,1,1,0

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
y = df.rating
x = df.drop('rating',axis=1)

In [21]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [22]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

In [23]:
gbm_model = GradientBoostingRegressor()
gbm_model.fit(X_train, y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

PREDICTION

In [24]:
y_pred = gbm_model.predict(X_test)
np.sqrt(mean_squared_error(y_test, y_pred))

5.828338876533024

In [25]:
gbm_model.score(X_test,y_test)

0.8344353392835451

MODEL TUNING

In [26]:
gbm_params = {
    'learning_rate': [0.001, 0.01, 0.1, 0.2],
    'max_depth': [3, 5, 8,50,100],
    'n_estimators': [200, 500, 1000, 2000],
    'subsample': [1,0.5,0.75],
}

In [27]:
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score

In [28]:
gbm = GradientBoostingRegressor()
gbm_cv_model = GridSearchCV(gbm, gbm_params, cv = 10, n_jobs = -1, verbose = 2)
gbm_cv_model.fit(X_train, y_train)

Fitting 10 folds for each of 240 candidates, totalling 2400 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    4.0s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:   18.9s
[Parallel(n_jobs=-1)]: Done 357 tasks      | elapsed:   56.6s
[Parallel(n_jobs=-1)]: Done 640 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-1)]: Done 1005 tasks      | elapsed:  2.6min
[Parallel(n_jobs=-1)]: Done 1450 tasks      | elapsed:  3.6min
[Parallel(n_jobs=-1)]: Done 1977 tasks      | elapsed:  4.4min
[Parallel(n_jobs=-1)]: Done 2400 out of 2400 | elapsed:  5.1min finished
/opt/conda/lib/python3.6/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=GradientBoostingRegressor(alpha=0.9,
                                                 criterion='friedman_mse',
                                                 init=None, learning_rate=0.1,
                                                 loss='ls', max_depth=3,
                                                 max_features=None,
                                                 max_leaf_nodes=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=100,
                                                 n_ite...
                                                 presort='auto',
                                                 random_state=None,
                                                 subsample=1.0, tol=0.0001,
                                                 validation_fraction=0.1,
                                                 verbose=0, warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 0.2],
                         'max_depth': [3, 5, 8, 50, 100],
                         'n_estimators': [200, 500, 1000, 2000],
                         'subsample': [1, 0.5, 0.75]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

In [29]:
gbm_cv_model.best_params_

{'learning_rate': 0.2,
 'max_depth': 100,
 'n_estimators': 1000,
 'subsample': 0.5}

In [30]:
gbm_tuned = GradientBoostingRegressor(learning_rate = 0.1,  
                                      max_depth = 50, 
                                      n_estimators = 1000, 
                                      subsample = 0.5)

gbm_tuned = gbm_tuned.fit(X_train,y_train)

In [31]:
y_pred = gbm_tuned.predict(X_test)
np.sqrt(mean_squared_error(y_test, y_pred))

4.2999498407254375

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
gbm_tuned.score(X_test, y_test)#test accuracy score

0.9098833928044137